### ISSUE TITLE
Bug using useState and onOptionHighlight

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#1]
Hi, I'm trying to set a flag when there not options to show, but if I use the `useState` hook in `onOptionHighlight` the component stops working; it doesn't show any option. 

if I use `console.log` it works as expected, I'm missing something?

```js
const [extraOptions, setExtraOptions] = useState(false);

  return (
    <AutoComplete
      onOptionHighlight={(value) => setExtraOptions(!value)} <!---
    >
    ...
    </AutoComplete>
```

EDIT:

using the `onChange` prop with `useState` have the same behavior

EDIT2: 

I think the problem is I'm using the component as uncontrolled, I tried to use it with `react-hook-form` but I couldn't. `AutoComplete` or `AutoCompleteInput` does not exposes the `value` prop

**Comment by anubra266** [comment]
I'm sorry I didn't get to you earlier. I'll check my settings, to know why I did not receive notifications. 
Mean time, I'll work on this ASAP.

**Comment by anubra266** [comment]
You should know this happened because I used a third party package for global state management. I've rewritten it in React context.

**Comment by gepd** [comment]
I was debugging the problem for some hours and I realized the problem was that (`easy peasy` lib), your latests changes looks pretty good I'm just waiting the new version to test it.

by the way, thanks for this component!
