### ISSUE TITLE
Console.log in use-autocomplete.ts:312

### ISSUE THREAD

**Issue by wkrasnicki** [anubra266/choc-autocomplete#100]
As the title says, version 4.11.5 has a console.log statement in tn line 312 of `use-autocomplete.ts`

**Comment by anubra266** [comment]
Thanks a lot @wkrasnicki  fixed in [v4.11.6](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.11.6)

**Comment by f-laino** [comment]
Also https://github.com/anubra266/choc-autocomplete/blob/main/src/use-autocomplete.ts#L184

**Comment by anubra266** [comment]
Thanks @f-laino
