### ISSUE TITLE
AutoCompleteTag label switches to value with `multiple`

### ISSUE THREAD

**Issue by chr-ge** [anubra266/choc-autocomplete#101]
Hello, 
I've found a bug with the `AutoCompleteItem` and the `AutoCompleteTag` with the `multiple` prop:

When I select an item from the suggestion that has a custom label and search for something in the input, the tag label switches to its value. This happens when my `data` array (array being mapped over in AutoCompleteList) changes while typing.

My `AutoComplete`:
```tsx
<AutoComplete
  multiple
  creatable
  rollNavigation
>
  ... 
</AutoComplete>
```

Here is my `AutoCompleteItem`:
```tsx
<AutoCompleteItem
   key={`option-${hashtag._id}`}
   value={hashtag._id}
   label={hashtag.value}
>
  {hashtag.value}
</AutoCompleteItem>
```

And my `AutoCompleteTag`:
```tsx
<AutoCompleteTag key={i} label={tag.label} onRemove={tag.onRemove} />
```

Here is a [codesandbox](https://codesandbox.io/s/chakra-autocomplete-bug-2h1lm?file=/pages/index.tsx).

**Comment by anubra266** [comment]
Hi @chr-ge change your `setData` to
```js
return setData((prevData) => [
        ...prevData,
        { id, value: "Number " + id }
      ]);
```

I don't have an indepth explanation but passing a function to `setState` methods, exposes the previous state, which you can utilise in setting the next state. directly using the existing state can cause confused mutations. Even worse now that you're using `setInterval`.

Happy coding.

**Comment by chr-ge** [comment]
Thanks, @anubra266! Is it possible to have a function called on create? I want to make a post request whenever a new item is created? Thanks

**Comment by anubra266** [comment]
> Thanks, @anubra266! Is it possible to have a function called on create? I want to make a post request whenever a new item is created? Thanks

Cool @chr-ge please create a feature request issue
