### ISSUE TITLE
Input with InputGroup does not span full width

### ISSUE THREAD

**Issue by margalit** [anubra266/choc-autocomplete#103]
`AutoCompleteInput` within `InputGroup` does not behave the same as `Input` within `InputGroup`:

![image](https://user-images.githubusercontent.com/2268424/145903510-38e1884e-a674-4573-a6a2-2bd7f1034221.png)

**Comment by AshMW2724** [comment]
Having the same issue
![image](https://legal-loli.art/8ErRcO7rPY.png)

[View on CodeSandbox](https://codesandbox.io/s/nervous-andras-hqqkz?file=/pages/index.tsx)
