### ISSUE TITLE
[Feature Request]: Expose way to trigger selecting the current item when spacebar is pressed

### ISSUE THREAD

**Issue by jamesopti** [anubra266/choc-autocomplete#105]
I'm using this library to capture email addresses. When the user types the space key, I'd like to be able to submit the current item.

**Ideas:**
- Expose `selectItem` to callers in the ref: https://github.com/anubra266/choc-autocomplete/blob/main/src/autocomplete.tsx#L31-L34
- Expose a prop to allow specific keys to trigger item selection (e.g. `submitKeys={['Enter', ',', ' ']}`)

**Comment by anubra266** [comment]
@jamesopti is this usecase multiple mode?

**Comment by jamesopti** [comment]
> @jamesopti is this usecase multiple mode?

Yup! We allow collecting multiple emails using this component, and since space is not a valid email character, the expectation is that space submits the current entry, just like return. (Gmail does this for example)

<img width="398" alt="Screen Shot 2022-01-05 at 9 06 22 AM" src="https://user-images.githubusercontent.com/3718812/148258774-a830a38f-7dc0-4ab3-9f9a-d80065eb713c.png">

**Comment by anubra266** [comment]
@jamesopti the package uses `event.key`, so If you're going to access space character, it would be `submitKeys={[" "]}`

**Comment by jamesopti** [comment]
> @jamesopti the package uses `event.key`, so If you're going to access space character, it would be `submitKeys={[" "]}`

Awesome, thank you @anubra266  for the quick turnaround!

**Comment by anubra266** [comment]
@jamesopti It's available in [v4.15.0](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.15.0), you're welcome
