### ISSUE TITLE
Wrong npm build

### ISSUE THREAD

**Issue by thalesog** [anubra266/choc-autocomplete#107]
The NPM build is pointing to datetimepicker instead of autocomplete package

![image](https://user-images.githubusercontent.com/4792793/149326308-23652609-7c81-43a6-af18-6d5c12711291.png)

![image](https://user-images.githubusercontent.com/4792793/149326812-36df8c71-8844-4e59-bbab-07d03a5b4f0e.png)

**Comment by anubra266** [comment]
Yeah...I made a mistake while trying to publish the other package.

**Comment by thalesog** [comment]
I think you can publish a updated version with the correct package and npm will release as latest

**Comment by anubra266** [comment]
I've been able to unpublish it @thalesog
