### ISSUE TITLE
Can't set async options via useState hook

### ISSUE THREAD

**Issue by jpc0rrea** [anubra266/choc-autocomplete#114]
I'm having a error when trying to set the options via useState hook. My code:

    import { KeyboardEventHandler, useState } from 'react';
    
    import {
      AutoComplete,
      AutoCompleteInput,
      AutoCompleteItem,
      AutoCompleteList,
    } from '@choc-ui/chakra-autocomplete';
    import { Competition } from '../../../../../lib/Scores365/types';
    import { competitionImageFrom365Scores } from '../../../../../utils/imagesFrom365Scores';
    import debounce from 'lodash.debounce';
    import { nextApi } from '../../../../../lib/api';
    import { Text } from '@chakra-ui/react';
    
    export default function SelectCompetition() {
      const [competitions, setCompetitions] = useState<Competition[]>(
        [] as Competition[]
      );
    
      const onKeyDown: KeyboardEventHandler<HTMLInputElement> = async (event) => {
        const target = event.target as HTMLInputElement;
    
        const keyWord = target.value;
    
        const competitionsResponse = await nextApi.get<{
          competitions: Competition[];
        }>(`scores365/getCompetitions?keyWord=${keyWord}`);
    
        const { competitions } = competitionsResponse.data;
    
        console.log(competitions);
    
        setCompetitions(competitions);
      };
    
      const debouncedKeyDown = debounce(onKeyDown, 500);
    
      return (
        <AutoComplete openOnFocus>
          <AutoCompleteInput variant="filled" onKeyDown={debouncedKeyDown} />
          <AutoCompleteList>
            {competitions?.map((competition) => (
              <AutoCompleteItem key={competition.id} value={competition.id}>
                <img
                  src={competitionImageFrom365Scores(competition.id)}
                  alt={`${competition.name} logo`}
                  className="px-2"
                />
                <Text>{competition.name}</Text>
              </AutoCompleteItem>
            ))}
          </AutoCompleteList>
        </AutoComplete>
      );

    }

The error: 

<img width="867" alt="Captura de Tela 2022-01-27 às 10 38 23" src="https://user-images.githubusercontent.com/56732309/151370226-ed5ef057-b4b6-405b-89e9-f90dd34c559d.png">

The API call is fine, I can import the `competitions` and show then on the console, I just can't make it as my options.

This is my `Competition` interface: 

        export interface Competition {
          id: number;
          countryId: number;
          sportId: number;
          name: string;
          popularityRank: number;
          nameForURL: string;
        }

**Comment by anubra266** [comment]
@jpc0rrea The `AutoCompleteItem` is expecting a `value` prop, and optionally a `label` prop which does not exist on the `Competition` interface

**Comment by anubra266** [comment]
@jpc0rrea According to the error, the problem is not from this package. You can try reproducing this in codesandbox. Feel free to reopen if you find something new

**Comment by kingjulien1** [comment]
Is this possible though in principle? I am trying to dynamically render the Items, but the list won't update until I reopen the list. Is there any way to manually trigger a re-render of the items? @anubra266
