### ISSUE TITLE
noOptionsMessage prop on AutoCompleteList

### ISSUE THREAD

**Issue by jpc0rrea** [anubra266/choc-autocomplete#115]
It would be nice if we have a `noOptionsMessage` on the `<AutoCompleteList />` component, so we can customize the "No options found!" message. 

The usage would be something like this:

      <AutoCompleteList noOptionsMessage="Não foi possível achar uma opção">
        {competitions?.map((competition) => (
          <AutoCompleteItem key={competition.id} value={competition.id}>
            <img
              src={competitionImageFrom365Scores(competition.id)}
              alt={`${competition.name} logo`}
              className="px-2"
            />
            <Text>{competition.name}</Text>
          </AutoCompleteItem>
        ))}
      </AutoCompleteList>

**Comment by anubra266** [comment]
@jpc0rrea `AutoComplete` accepts an `emptyState` prop for this purpose, and you can pass react components to it and not just strings.
```html
<AutoComplete emptyState={<div>No countries match your search </div>} />
```

 Please check the Readme for more details
