### ISSUE TITLE
Expose full value object in `onSelectOption`

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-autocomplete#117]
Alright I just got it all setup again and this was the issue... 

``` typescript
<AutoCompleteItem
  key={idx}
  value={address}
  getValue={(address: AddressRecommendation) => address.address}
>
  {address.address}
</AutoCompleteItem>
```
The above works as expected, but when I select an item and set a debugger within `onSelection`, here's what `selectedOption` is:
![image](https://user-images.githubusercontent.com/6445731/151414074-8d62f36c-d142-4efb-a1e1-ffe727a4c444.png)

For my use case, I would expect `selectedOption.item.value` to be the full object so I could set the selected `address` and `placeId`, not just the value of the key I provided in `getValue`. Make sense? I wouldn't make this change without getting input from others, especially since it's a breaking change, but hopefully that clears up what my intent was.

_Originally posted by @SpencerKaiser in https://github.com/anubra266/choc-autocomplete/issues/60#issuecomment-1023484143_

**Comment by SpencerKaiser** [comment]
@anubra266 what are your thoughts on how to expose that? Think replacing `value` would be best or do you think a new attribute should be added there?

The former is a breaking change, but I think it'd be clearer to the user. Not really sure what the best approach would be.

**Comment by anubra266** [comment]
@SpencerKaiser  I'm trying to avoid breaking changes, so I was thinking:
1. add a `itemObj` key to `label` and `value`,
2. Just populate `item` with the keys in the itemObject. so we have `label`, `value` and the rest e.g. `address`

**Comment by SpencerKaiser** [comment]
Sorry for the delay, yea that's a good call! I think that's a solid workaround.

**Comment by jcdogo** [comment]
I don't think that is a good idea to merge the objects.  What if the full object already has a `label` and `value` field? Then you'll have a key collision if you try to merge the fields from the full object into `item`.

**Comment by jcdogo** [comment]
In my opinion having the `value` in the `item` not match the `value` passed to `AutoCompleteItem` is sort of a bug.  It's confusing that they are not the same. One would expect that if you pass in a value you get the same value back when selected. 

Although it's a breaking change to change it to the full object, I think it's the solution that makes the most sense in the long run.

If you really don't want to introduce a breaking change, you can just add a `objValue` or something to `item` that contains the original value object.
