### ISSUE TITLE
Feature: Reset value when onBlur occurs

### ISSUE THREAD

**Issue by iamclaytonray** [anubra266/choc-autocomplete#118]
If `creatable={false}`, when onBlur fires off, another value should be selected instead of keeping the previously typed text.

As much as I dislike MUI, it's the fastest example I could think of: https://mui.com/components/autocomplete/#main-content

**Comment by anubra266** [comment]
@iamclaytonray when you blur, the last selected value is selected. Could you shed more light on the behaviour you're expecting?
