### ISSUE TITLE
Feature: keyboard navigation, no scroll on arrows and tabbing

### ISSUE THREAD

**Issue by wkrasnicki** [anubra266/choc-autocomplete#123]
Hello, I would like to propose some quality of life improvements to the keyboard navigation. First of all, when selecting suggestions using arrows, the page scrolls upon pressing arrow down or up. I think it would be better if we prevented the default scrolling action when the suggestion list is open or at least add a prop to do so.

The other issue has to do with tabbing. Currently I have a form, where the autocomplete is one of the fields. I can focus it by tabbing into it, but I can't leave it afterwards with either `Shift`+`Tab` or just `Tab`. I'm not even sure which element is being focused, so it's hard for me to find a workaround for this.

**Comment by anubra266** [comment]
@wkrasnicki can you create a codesandbox reproduction of this please. Thanks

**Comment by matt-dale** [comment]
Here's a repo of the scrolling action issue.

https://codesandbox.io/s/choc-ui-scrolling-issue-brkwtd

I believe Chakra-UI uses [this RemoveScroll package](https://github.com/theKashey/react-remove-scroll#readme) for Modals and toggles it on/off with the `blockScrollOnMount` prop.

**Comment by matt-dale** [comment]
Here is a reproduction of the tab issue. Once the AutoCompleteList is open (in this case `openOnFocus` is true), the user can't use the keyboard to exit the AutoComplete unless they select an option.

https://codesandbox.io/s/choc-ui-focus-trap-zrr5hd?file=/src/index.js

**Comment by anubra266** [comment]
I see @matt-dale. It's because `Tab` can be used to navigate the input

**Comment by Kysluss** [comment]
This can be closed.  I didn't realize I didn't link it to #188 when I created the PR.
