### ISSUE TITLE
Feature: "fixed" prop regardless of "maxSuggestions"

### ISSUE THREAD

**Issue by daliudzius** [anubra266/choc-autocomplete#124]
I'm using `AutoCompleteGroup` to show a divider then a `fixed` custom item (eg. Show All Categories) that should always be at the end of the suggestions -- however when limiting suggestions to a small number the `fixed` item doesn't show if the suggestions are maxed out. 

Solution ideas:
- Make `fixed` item show even when suggestions reach `maxSuggestions`.
Or
- Include `maxSuggestions` prop for individual `AutoCompleteGroup` that would apply only to that grouping.
Or
- Make a separate `alwaysShow` item that's present regardless of 'maxSuggestions`.

Attached gif shows the `AutoCompleteItem` ("Show All Categories") I have after an `AutoCompleteGroup` that is intended to show after the regular suggestions, however it only shows if total suggestions < `maxSuggestions={3}`

![CPT2202141542-804x540](https://user-images.githubusercontent.com/46355846/153965799-494319cb-23c7-450a-976a-411079ecd463.gif)

**Comment by anubra266** [comment]
Hi @daliudzius Could you create a codesandbox reproduction of this? thanks

**Comment by daliudzius** [comment]
@anubra266 Sure, here you go: https://codesandbox.io/s/dazzling-mclean-pkqxw?file=/src/with-icon.js

## Usage

- If you type "d" it displays the 2 suggestions + the `fixed` item that is intended to always be in the suggestions regardless of `maxSuggestions` limit.
- If you type "a" it displays 3 suggestions according to `maxSuggestions` however does not take into account the `fixed` item which would be at the end of the array of suggestions.

## Additional notes
I created a pull request you with an idea of adding another prop `alwaysShow` which would behave similar to `fixed`, although it would show regardless of both `filter` and `maxSuggestions`.

**Comment by anubra266** [comment]
@daliudzius i think it will be better if we tweak fixed to always show instead of adding a new prop that aims to do the same thing.

**Comment by daliudzius** [comment]
Agreed, @anubra266. I was hesitant to suggest that in the event that I was missing some use case for `fixed` to function within the scope of `maxSuggestions` as it currently does.
