### ISSUE TITLE
Use of `isInvalid` triggers warning

### ISSUE THREAD

**Issue by SpencerKaiser** [anubra266/choc-autocomplete#126]
@anubra266 so the `isInvalid` prop on the input component works as expected from a UI perspective (red highlight), BUT it seems to trigger an error:
```
Warning: React does not recognize the `isInvalid` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isinvalid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Repro code:
``` typescript
<AutoComplete>
  <AutoCompleteInput isInvalid={true}></AutoCompleteInput>
</AutoComplete>
```

Any idea what I'm doing wrong?

_Originally posted by @SpencerKaiser in https://github.com/anubra266/choc-autocomplete/issues/122#issuecomment-1039749162_

**Comment by SpencerKaiser** [comment]
@anubra266 any idea what could be going on with this one? 🤔

**Comment by anubra266** [comment]
@SpencerKaiser is it a standard one or the multiple Autocomplete?

**Comment by SpencerKaiser** [comment]
Standard, nothing crazy added in

**Comment by kculmback-eig** [comment]
Same thing happens with `isDisabled` for us if `multiple` prop is set on `AutoComplete`

```jsx
<AutoComplete multiple>
  <AutoCompleteInput
    isDisabled={disabled}
  >
    {/* ... */}
</AutoComplete>
```
