### ISSUE TITLE
Allow Creatable to be Shown before typing 

### ISSUE THREAD

**Issue by chrisgco** [anubra266/choc-autocomplete#129]
It would be convenient to have a prop on `AutoComplete` that allows the createable item to be shown before any text is input.

<img width="376" alt="Screen Shot 2022-03-03 at 2 10 21 PM" src="https://user-images.githubusercontent.com/3736842/156571296-310b49e9-f6e6-4588-a997-bb817dfec803.png">
 
In this example the user sees the option to create a new client but can still type to filter the existing ones. As soon as the user types the creatable option disappears. If the user has typed in text for which there is no corresponding option, the creatable item reappears.

This doesn't seem to be possible given the current options.

**Comment by anubra266** [comment]
Hi @chrisgco I'm not sure what exactly you're requesting, but Is a prop that makes creatable show while input is empty, or is there something else in addition to that?

**Comment by chrisgco** [comment]
Hey @anubra266, exactly what you said. It just makes creatable shown while input is empty

**Comment by anubra266** [comment]
@chrisgco there's now an `alwaysDisplay` prop in `AutoCompleteCreatable` as at [4.18.0]()
