### ISSUE TITLE
TypeError: null is not an object (evaluating 'child.type')

### ISSUE THREAD

**Issue by chrisgco** [anubra266/choc-autocomplete#130]
If there is a conditionally rendered element (sometimes null) in the children of `AutoCompleteList` it crashes. I think it's related to this line:

https://github.com/anubra266/choc-autocomplete/blob/9adedd56bd23440be8dee08c33b8c1d241d16847/src/helpers/list.ts#L5

The solution may just be adding a `?.` after `child`

**Comment by anubra266** [comment]
Fixed in [4.18.1](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.18.1)
