### ISSUE TITLE
Feature: Ability to pass a component to AutoCompleteList to use as the null fallback

### ISSUE THREAD

**Issue by fernpolo** [anubra266/choc-autocomplete#134]
In the current configuration, when there isn't anything to show, `AutoCompleteList` shows the predefined `EmptyState` ("_No options found!_") component. There's obviously no way to change this other forking or ~~downloading~~ saving the library.

A great addition to this library would be the ability to pass a component (to `AutoCompleteList`) that could be used instead!

A good use for customising this message would be for a user-generated content application offering users a link to create whatever is being searched (e.g., account, etc).

**Comment by anubra266** [comment]
Hi @fernpolo `emptyState` is a boolean/ReactNode type
<img width="729" alt="CleanShot 2022-03-10 at 02 01 59@2x" src="https://user-images.githubusercontent.com/30869823/157566282-a6d3be25-1236-4b56-a471-478e80c79a55.png">

You can do 
```tsx
<AutoComplete emptyState />
```
or
```tsx
<AutoComplete emptyState={<div>Empty Message</div>} />
```
and even 
```tsx
<AutoComplete emptyState={({ value }) => (<div> {value} not found </div> )} />
```
