### ISSUE TITLE
Asynchronous Request

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#139]
There is any way to make Asynchronous request with the current status of this component?

I'm looking to make a request as I type but I haven't found a way yet

Reference: https://mui.com/components/autocomplete/#search-as-you-type

**Comment by anubra266** [comment]
@gepd Just map your items from a state. And update the items with the results of your search.
Controlled search keyword with Input
```html
 <AutoCompleteInput
    value={query}
    onChange={e => setQuery(e.target.value)}
 />
```
Do search logic based on the query, and do something like `setList(searchResults)` - with `useState` setter

Then map`list` each item as `AutoCompleteItem`

**Comment by kingjulien1** [comment]
Is this possible though in principle? I am trying to dynamically render the Items, but the list won't update until I reopen the list. Is there any way to manually trigger a re-render of the items? @anubra266
