### ISSUE TITLE
Props Request: Show menu when input field is focused

### ISSUE THREAD

**Issue by TaylorFacen** [anubra266/choc-autocomplete#14]
Because the select options aren't displayed when the user clicks the input field, they have to type random letters just to see what options are available. It would be helpful to have the option to see all available options before typing anything.

**Comment by anubra266** [comment]
There's a `suggestWhenEmpty` prop.

**Comment by TaylorFacen** [comment]
I see it now. In the docs it's a bit buried in the selectOnFocus row.

**Comment by anubra266** [comment]
Ah...thanks!

**Comment by TaylorFacen** [comment]
Actually, I have a quick question on this @anubra266 , I see that if I provide a default value, the menu is already filtered. Is there a way to show all options even when there's a default value and only filter once the input has changed? The use case is, the user is able to manage financial transactions and assign a category to each transaction. I want them to be able to edit a transaction's category. So when they go to edit the transaction, there's already a pre-filled category that they have the option to change. I want them to be able to see all options even if there's already a category value.

**Comment by anubra266** [comment]
That makes sense, could you open a feature request issue? Thanks.

**Comment by anubra266** [comment]
@TaylorFacen You can now use the `initialFilter` prop on the `AutoCompleteInput` from v3.3.0
