### ISSUE TITLE
AutoCompleteCreateable returning react object

### ISSUE THREAD

**Issue by nimo-juice** [anubra266/choc-autocomplete#141]
https://github.com/anubra266/choc-autocomplete/blob/main/src/autocomplete-creatable.tsx#L24

`AutoCompleteCreatable` is returning a react object -- it's wrapping the input value in a `mark` tag. This prevents us from using that value in translation strings or manipulating the text directly.

**Comment by anubra266** [comment]
@nimo-juice Changed this in [v4.20.2](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.20.2)

**Comment by nimo-juice** [comment]
Amazing, thank you <3
