### ISSUE TITLE
Keep suggestions popover open after selection then refilter

### ISSUE THREAD

**Issue by dn00** [anubra266/choc-autocomplete#145]
This is the behavior when _multiple_ is true. Popover suggestions stays open and filter out each selection. How can I achieve this for simple input? I'm building some sort of pseudo file browser and need the popover to stay open as well as filter out options that does not startWith a value (file path).

**Comment by anubra266** [comment]
@dn00 I don't fully understand, but you can keep it open by setting `closeOnSelect` to `false`, and you can use the `filter` prop for custom filtering. Check the readme props for usage.
