### ISSUE TITLE
PROJECT MAINTENANCE. 

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-autocomplete#147]
I've been having a lot going on for a while now, and it's just not going to be easy maintaining this project as well.
If anyone wants to help maintain it, please feel free to contact me on twitter @anubra266.
There are lots of open issues right now, and I can't promise that I can fix them soon.

If the open issues are affecting your work's progress. I'll recommend React Aria's combobox. It handles majority of usecases, handles accessibility too. And an example built in chakra UI is here: https://codesandbox.io/s/dreamy-burnell-3i2jy?file=/src/App.tsx

I'm really sorry that I can't give more attention to this.
Thank you.

**Comment by anubra266** [comment]
> Hi @anubra266 ,
> 
> I'm using this library in a project in production, I'd like to continue using it, can I help to maintain it?
> 
> Let me know, thanks

Yes you can @Richi2293

**Comment by Kysluss** [comment]
Hi @anubra266 

I would also like to help maintain the project.  I have opened a handful of PRs to fix some issues and add a couple of feature requests.  Let me know if there's anything else I can help with.  Thank you for this great package!

**Comment by anubra266** [comment]
@Kysluss Can you send your email, I'll give you access to the repo.
Also your username on `npmjs.com` so you have permissions publish the package

**Comment by Kysluss** [comment]
> @Kysluss Can you send your email, I'll give you access to the repo. Also your username on `npmjs.com` so you have permissions publish the package

Attempted to email you via your blog.  If you don't get it, let me know.  Thank you again!

**Comment by anubra266** [comment]
@Kysluss I've sent the invites
