### ISSUE TITLE
Creatable not working

### ISSUE THREAD

**Issue by Hanskrogh** [anubra266/choc-autocomplete#148]
Examples seems to not be working and codesandbox is not working either. The `<AutoCompleteCreatable>` when added is removing all suggestions. When you type something that is already in the option list, it shows both "Create this option" and the options that already exist. It seems really bugged and the documentation on how to use it, is non existing...

Could you update the examples / documentation?

**Comment by realjesset** [comment]
yeah suggestions don't show when `creatable` is passed

**Comment by Derad6709** [comment]
Any updates on it?

**Comment by Daidalos117** [comment]
Did you solve it somehow guys?

**Comment by anubra266** [comment]
Releaeed [v5.1.4](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.1.4)
