### ISSUE TITLE
Feature Request: Prop to Show unfiltered items with input defaultValue

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-autocomplete#15]
As per @TaylorFacen 's request in #14  
>I see that if I provide a default value, the menu is already filtered. Is there a way to show all options even when there's a default value and only filter once the input has changed? The use case is, the user is able to manage financial transactions and assign a category to each transaction. I want them to be able to edit a transaction's category. So when they go to edit the transaction, there's already a pre-filled category that they have the option to change. I want them to be able to see all options even if there's already a category value.

**Comment by anubra266** [comment]
This will be achieved by applying setting `initialFilter` prop to `false` on the `AutoCompleteInput` component.

**Comment by TaylorFacen** [comment]
Thanks!
