### ISSUE TITLE
Missing index.es.js from release

### ISSUE THREAD

**Issue by emlyn-arkahna** [anubra266/choc-autocomplete#157]
I'm getting the following error when attempting to import choc-autocomplete
![image](https://user-images.githubusercontent.com/84910463/187112681-273bf27c-19e8-4b61-8b62-8cb1a911f0a9.png)

It appears that the module file `dist/index.es.js` specified in `package.json` does not exist
![image](https://user-images.githubusercontent.com/84910463/187113256-506db5d2-677e-4261-9f0e-94d20ba0ecbc.png)

removing the module prop from `package.json` resolves the issue

**Comment by bielas** [comment]
@anubra266 when do you plan to fix that? @emlyn-arkahna any suggestion of workaround?

**Comment by anubra266** [comment]
@emlyn-arkahna, @bielas should be fixed in [v5.1.2](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.1.2)

**Comment by bielas** [comment]
Is is already released?

**Comment by anubra266** [comment]
> Is is already released?

Yeah
