### ISSUE TITLE
Groups not working

### ISSUE THREAD

**Issue by ImExoOdeex** [anubra266/choc-autocomplete#159]
In [**live example**](https://codesandbox.io/s/github/anubra266/choc-autocomplete/tree/main/demo?file=/src/group.js) group does not work. I followed the tutorial and its not working. Can someone fix this?

**Comment by Kysluss** [comment]
Looks like this was fixed in [this PR](https://github.com/anubra266/choc-autocomplete/pull/165) and can be closed now.  Looking at the live example, the groups are working as expected.
