### ISSUE TITLE
feature request: multi-selection

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#16]
Would be good to have multi selection, this is one of the features that even the [chakra select](https://chakra-ui.com/docs/form/select) component have missing

Use the [tag](https://chakra-ui.com/docs/data-display/tag) component would be a good option

reference: https://material-ui.com/components/autocomplete/#multiple-values

**Comment by matheusmb** [comment]
Definitely would be nice to have this feature!

**Comment by anubra266** [comment]
Hi @gepd I'm about to work on this. I would love to have your input on the structure that would be best for this. Such that you have the flexibility of rendering the input and the internal tags. I just need a sample of the way you think would be best as an end user. E.g. 
```tsx
<AutoCompleteMultiInput>
     {({tags})=>(
            <AutoCOmpleteTag/>
       )
     }
<AutoCompleteMultiInput/>

**Comment by gepd** [comment]
Hi @anubra266, I like the flexibility of this component, would be great to have something as your example. I imagine that `tags` will export the label and value, and maybe a callback to remove the tag or maybe that you will handle internally (?).

Will you allow to use the tag with custom elements like in the chakra example? https://chakra-ui.com/docs/data-display/tag#with-custom-element

**Comment by anubra266** [comment]
@gepd, I'll leave rendering tags to the end user so it's possible to use any component, Tags or something else, but the tags, will expose all required variables and methods.

**Comment by anubra266** [comment]
Coming up in the next release
