### ISSUE TITLE
Bad css in dark color mode and variant `filled` with Next.js.

### ISSUE THREAD

**Issue by tresorama** [anubra266/choc-autocomplete#167]
# Description

If color mode is `dark` and `<AutoCompleteInput  />` has `variant="filled"` background color of `<input />` is not ok.

# How to reproduce

1. Open sandbox
[Codesandbox](https://codesandbox.io/s/chakra-autocomplete-filled-dark-bug-vcdide?file=/pages/index.tsx)
2. Look correct css in `light` mode
3. Look bad css in `dark` mode

## Additional Info

It seems a bug that happens only when used with Next.js.

**Comment by OlivierLESAGE** [comment]
same issue here, looks like the background color in dark mode is wrong

**Comment by Kysluss** [comment]
I'm a bit baffled on this one.  The only thing I've figured out is that the input element doesn't seem to switch between dark and light mode.  It is always in light mode (the CSS class stays the same if you toggle).  Might need a guiding hand from @anubra266 if you have time.  I tried updating all of the packages just to make sure that wasn't it [in this fork](https://github.com/Kysluss/choc-autocomplete/tree/167-dark-mode).  I also tried to trace through to make sure the variant is passed to the Input along with other props.

I'm wondering if this is a build issue or something else altogether.  I installed the package via npm and also copied the source files to a separate folder and rand them side by side.  The local copy correctly toggled dark/light mode, but the npm package did not.  I tried to create a code sandbox, but couldn't seem to get it working right so created [this repo](https://github.com/Kysluss/choc-ui-autocomplete-dark-mode-example).  Steps are below

1. Create a new typescript project using `npx create-react-app my-app --template typescript`
2. cd into my-app and run `npm install @choc-ui/chakra-autocomplete`
3. Copy files from original source into autocomplete folder
4. Create ChocAutocomplete and LocalAutocomplete components
5. Update App.tsx to use the two side by side and add a color mode toggle button

**Comment by Kysluss** [comment]
This is fixed now in [v5.2.1](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.2.1)

A quick description of what happened here was an issue with the build process that was causing multiple Chakra contexts to be created.  The one used by this project would essentially always be empty after initial load, so the `Input` (and other) elements were essentially locked into their initial color mode on load.

I wanted to update to the latest version of vite anyway, so took the opportunity to redo the build process.

**Comment by tresorama** [comment]
Great , will take i look when time permits :)

**Comment by tresorama** [comment]
Tested in this sandbox:
[Codesandbox](https://codesandbox.io/p/devbox/chakra-autocomplete-filled-dark-bug-forked-dgm57w?file=%2Fpages%2Findex.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluu31d1x00073b6jw4y5wx22%2522%252C%2522sizes%2522%253A%255B77.27698305449853%252C22.72301694550147%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluu31d1w00033b6jwh3d9ej8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluu31d1w00053b6jpxoljbor%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluu31d1w00063b6j0pbycao5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B66.14319647840563%252C33.85680352159437%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluu31d1w00033b6jwh3d9ej8%2522%253A%257B%2522id%2522%253A%2522cluu31d1w00033b6jwh3d9ej8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluu37qli00023b6kap5n5v1f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A44%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A44%252C%2522endColumn%2522%253A31%257D%255D%252C%2522filepath%2522%253A%2522%252Fpages%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluu37qli00023b6kap5n5v1f%2522%257D%252C%2522cluu31d1w00063b6j0pbycao5%2522%253A%257B%2522id%2522%253A%2522cluu31d1w00063b6j0pbycao5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cluu32jtz00cc3b6jqr8445ry%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluu32jtz00cc3b6jqr8445ry%2522%257D%252C%2522cluu31d1w00053b6jpxoljbor%2522%253A%257B%2522id%2522%253A%2522cluu31d1w00053b6jpxoljbor%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluu31d1w00043b6jw2doyat7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluu31ee4000kdiihgdw6g9vq%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cluu32j7900aq3b6jq2cva9i7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluu32j7900aq3b6jq2cva9i7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

It works! Thanks
