### ISSUE TITLE
AutoComplete.InputGroup does not respect InputLeftElement

### ISSUE THREAD

**Issue by karimcambridge** [anubra266/choc-autocomplete#17]
```js
import {
	InputGroup,
	InputLeftElement,
	InputRightElement,
	Icon,
} from '@chakra-ui/react';
import {
	AutoComplete,
	AutoCompleteInput,
	AutoCompleteItem,
	AutoCompleteList,
	AutoCompleteGroup,
	AutoCompleteFixedItem,
  } from '@choc-ui/chakra-autocomplete';
  import { SearchIcon, ChevronRightIcon, ChevronDownIcon } from '@chakra-ui/icons';

const SearchBar = props => {
	const options = ['apple', 'appoint', 'zap', 'cap', 'japan'];
  
	return (
		<AutoComplete rollNavigation>
			{({ isOpen }) => (
				<>
					<InputGroup>
						<InputLeftElement
							pointerEvents="none"
							children={<SearchIcon />}
						/>
						<AutoCompleteInput
							variant="filled"
							placeholder="    Search..."
						/>
						<InputRightElement
							pointerEvents="none"
							children={
								<Icon as={isOpen ? ChevronRightIcon : ChevronDownIcon} />
							}
						/>
					</InputGroup>
					<AutoCompleteList>
						{options.map((option, oid) => (
							<AutoCompleteItem
								key={`optio-${oid}`}
								value={option}
								textTransform="capitalize"
								align="center"
							>
								{option}
							</AutoCompleteItem>
						))}
					</AutoCompleteList>
				</>
			)}
		</AutoComplete>
	);
};

export default SearchBar;
```

Result is 
![image](https://user-images.githubusercontent.com/4283893/124061219-7e5de200-d9fc-11eb-8082-ba02ccfda026.png)

![image](https://user-images.githubusercontent.com/4283893/124061461-deed1f00-d9fc-11eb-8d60-372259c5ea74.png)

**Comment by anubra266** [comment]
Hi could you create a codesandbox reporoduction?

**Comment by karimcambridge** [comment]
Hi, honestly after playing around and switching things up a bit it actually seems like the issue is the Input component from chakra itself, I switched to that.

Also, check out the screenshots, look at how the icon overlaps with the placeholder / cursor.

> Hi could you create a codesandbox reporoduction?

**Comment by anubra266** [comment]
Hi @karimcambridge this is fixed in v3.5.1

**Comment by karimcambridge** [comment]
Also see someone reported something similar here

https://github.com/chakra-ui/chakra-ui/issues/4366

**Comment by anubra266** [comment]
I just found out the package is breaking with the latest Chakra version. The list is jumping off the page😔

**Comment by karimcambridge** [comment]
> I just found out the package is breaking with the latest Chakra version. The list is jumping off the page😔

Yea that is happening, I tried to report it. https://github.com/chakra-ui/chakra-ui/issues/4329

If you can help bring it to their attention, it needs to be fixed asap.
