### ISSUE TITLE
AutoCompleteList popover placement isn't 'auto'

### ISSUE THREAD

**Issue by patrickclover** [anubra266/choc-autocomplete#171]
Its not possible to change the default placement of the popover component, when its at the bottom of the page if forces the height of the page to re-adjust. 

Would be good to have access to popover props.

**Comment by Kysluss** [comment]
@patrickclover Would you be able to provide a screenshot or sandbox showing what you're looking for?  Judging by the question, it seems like you want to be able to statically define whether the list shows up above/below the input element?
