### ISSUE TITLE
Can't install library due to framer-motion issue

### ISSUE THREAD

**Issue by vitalijalbu** [anubra266/choc-autocomplete#175]
Using latest chakra ui version

![Screenshot 2023-03-20 alle 08 10 54](https://user-images.githubusercontent.com/40239902/226271395-8cc53f13-ad24-47a2-b527-3bbc56abbf4e.png)

**Comment by Richi2293** [comment]
Hi @vitalijalbu @nextglabs ,
try to use the latest version (v 5.1.6), the problem should be solved
