### ISSUE TITLE
deletion of input does not make full list reappear

### ISSUE THREAD

**Issue by cherylcarpenter** [anubra266/choc-autocomplete#184]
First page load and mouse click:
<img width="494" alt="image" src="https://github.com/anubra266/choc-autocomplete/assets/13105904/1eaa1195-0918-436a-ac13-a7b1247d9d32">

item selected, but then backspaced:
<img width="502" alt="image" src="https://github.com/anubra266/choc-autocomplete/assets/13105904/0ca48ab8-282d-450d-bedd-0f4601ad7fee">

If user clicks outside of input, while null selected, input goes back to old value.

How can this default behavior be changed?

**Comment by TheCryptoChad** [comment]
Add the `suggestWhenEmpty` prop to the `AutoComplete` wrapper component, that should do it.

**Comment by cherylcarpenter** [comment]
perfect! works, thank you. Sorry I missed that in the options :)
