### ISSUE TITLE
set "value" props doesn't change input value

### ISSUE THREAD

**Issue by Pupun2542** [anubra266/choc-autocomplete#193]
Hi. It seems like setting value as in the controlled component cannot change text value. Like this code, I set japan as the default value but the component shows blank instead.
I know I can set it in defaultValue but in my real use case, I cannot use defaultValue, since data can be manipulated by outside action and defaultValue won't change.
Or if this is intended, can you suggest how to handle controlled component?

"use client"
import React, { useState } from 'react'
import {
  AutoComplete,
  AutoCompleteInput,
  AutoCompleteItem,
  AutoCompleteList,
  AutoCompleteCreatable
} from "@choc-ui/chakra-autocomplete";
const Page = () => {
  const countries = [
    "nigeria",
    "japan",
    "india",
    "united states",
    "south korea",
  ];
  const [select, setSelect] = useState("japan")
  console.log(select)
  return (
    <AutoComplete openOnFocus value={select} onChange={(e)=>setSelect(e)}>
    <AutoCompleteInput variant="filled"/>
    <AutoCompleteList>
      {countries.map((country, cid) => (
        <AutoCompleteItem
          key={`option-${cid}`}
          value={country}
        >
          {country}
        </AutoCompleteItem>
      ))}
    </AutoCompleteList>
  </AutoComplete>
  )
}
export default Page

Thank you
<img width="908" alt="image" src="https://github.com/anubra266/choc-autocomplete/assets/25640747/7fb7c019-255d-42f0-9253-323747e78062">

**Comment by Kysluss** [comment]
Hi @Pupun2542,

I was able to get this working by passing the `value` prop directly to the `AutoCompleteInput` component.  Try that and let me know if it works for your use case.

**Comment by Pupun2542** [comment]
Hi @Kysluss,
With a bit of a workaround, I managed to get it to work. Thank you for a hint.
