### ISSUE TITLE
Why has react-nanny become a peer-dependency?

### ISSUE THREAD

**Issue by sakerhetspolisen** [anubra266/choc-autocomplete#213]
Since v5.2.1 and [this](https://github.com/anubra266/choc-autocomplete/commit/fb6df6563827ee4473ce90cdb2b830747143a409) commit `react-nanny` has been moved from deps to peer-deps. This results in the following _Module not found_-error in a project using the `choc-autocomplete` but not `react-nanny`:

![Screenshot from 2023-09-18 16 08 03](https://github.com/anubra266/choc-autocomplete/assets/68159964/02f2c589-7c20-4c57-a348-cbced0082ec5)

From the README of `react-nanny`: 
> Utils to manage your React Children; find and filter children by type or custom function, enforce child content, and more!

Is there a reason why it has been moved? If not, this change should be reverted.

**Comment by Kysluss** [comment]
Hello.  Thank you for the bug report and PR.  I have merged this into v5.2.6.

I had this fixed in a branch I'm working on to update some of the demos that just wasn't ready for release yet.
