### ISSUE TITLE
tabbing out of autocomplete input selects the focused item in multiple mode

### ISSUE THREAD

**Issue by Janekk** [anubra266/choc-autocomplete#228]
I've found an issue when using the autocomplete in the `multiple` mode. If I press the `Tab` key while the AutocompleteList is closed, it still selects the focused option. It seem this line has to do with it: https://github.com/anubra266/choc-autocomplete/blob/ffabbf7b45b66df387ead3034f9884888f88ea29/src/use-autocomplete.ts#L324

**Expected behavior**: the input should just blur and no extra selection should be made

Can we make it select item upon Tab press only if the autocomplete list is open?

**Comment by Kysluss** [comment]
Hello @Janekk and thank you for reporting this.  I think I was able to reproduce what you're saying with both multiple and single selects.  Let me know if the below sounds about right.

1. Click into the autocomplete (list opens)
2. Press escape (list closes, but focus remains)
3. Tab out of autocomplete (last focused item is selected)

**Comment by Kysluss** [comment]
This should be fixed in [v5.2.9](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.2.9), but let me know if the issue still happens and I'll re-open this issue.
