### ISSUE TITLE
Bug using AutoCompleteFixedItem and AutoCompleteGroup

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#23]
I have this list:

```html
<AutoCompleteList>
  <AutoCompleteGroup title="Title" showDivider>
    <AutoCompleteItem value="1">Apple</AutoCompleteItem>
    <AutoCompleteItem value="2">Appoint</AutoCompleteItem>
  </AutoCompleteGroup>
  <AutoCompleteFixedItem value="F1">Fixed Item 1</AutoCompleteFixedItem>
  <AutoCompleteFixedItem value="F2">Fixed Item 2</AutoCompleteFixedItem>
</AutoCompleteList>
```
And this is what I see, as you can see The `Fixed item 1` is duplicated

![image](https://user-images.githubusercontent.com/7091609/125544645-a009ab86-e062-40e6-92b9-2d71703ea4ec.png)

If I put the `FixedItem` Inside of the `AutoCompleteGroup` I can't see none of those items

**Comment by anubra266** [comment]
I've found a lot of bugs, while looking at this. One being if the value is not same as innerText, there's trouble. I'll try to fix this soon.

**Comment by gepd** [comment]
I just started to test it and I found this and the previous one, I'll wait for your fix to keep using this feature, thanks!

**Comment by anubra266** [comment]
Hi @gepd. Regarding the bug I talked about, what's happening is the filter only checks the value, not the text passed to `Item` component. I initially made it this way for, items that rendered whole components. What do you think of accepting a label prop, that is also filtered, or if you have a better way of addressing it.

**Comment by anubra266** [comment]
By the way, I'm unable to reproduce this issue

**Comment by gepd** [comment]
> Hi @gepd. Regarding the bug I talked about, what's happening is the filter only checks the value, not the text passed to `Item` component. I initially made it this way for, items that rendered whole components. What do you think of accepting a label prop, that is also filtered

Yes that sound great to me



> By the way, I'm unable to reproduce this issue

I tried again in a clean install (next.js) and yes, I don't see the duplication problem anymore, I'll check my first code to see where is the problem.

The second one, when the `FixedItem` does not show up inside a `AutoCompleteGroup` keep happening, I would like wrap it mostly to add a way to separate the fixed items from the `Items`

**Comment by anubra266** [comment]
> The second one, when the `FixedItem` does not show up inside a `AutoCompleteGroup` keep happening, I would like wrap it mostly to add a way to separate the fixed items from the `Items`

Hi @gepd , I don't understand this.

**Comment by gepd** [comment]
I mean, this does not work
```html
<AutoCompleteList>
  <AutoCompleteGroup title="Title" showDivider>
    <AutoCompleteItem value="1">Apple</AutoCompleteItem>
    <AutoCompleteItem value="2">Appoint</AutoCompleteItem>
  </AutoCompleteGroup>
  <AutoCompleteGroup title="Title2" showDivider>
    <AutoCompleteFixedItem value="F1">Fixed Item 1</AutoCompleteFixedItem>
    <AutoCompleteFixedItem value="F2">Fixed Item 2</AutoCompleteFixedItem>
    </AutoCompleteGroup>
</AutoCompleteList>
```
