### ISSUE TITLE
Last selected item in multi-select autocomplete prefills input on external click

### ISSUE THREAD

**Issue by Hagriel** [anubra266/choc-autocomplete#234]
After typing text in a multi-select autocomplete, and selecting an item from the dropdown, clicking outside the dropdown results in the last item being prefilled in the input field

<img width="740" alt="Screenshot 2023-12-28 at 7 13 47 PM" src="https://github.com/anubra266/choc-autocomplete/assets/28817316/704ea854-5356-449e-bcbf-53929c53405e">

**Comment by Hagriel** [comment]
the same in this example https://codesandbox.io/p/devbox/chakra-autocomplete-demo-jrk70

<img width="720" alt="Screenshot 2023-12-28 at 7 19 05 PM" src="https://github.com/anubra266/choc-autocomplete/assets/28817316/f7c9a32d-7a27-412a-9705-acd9861dc2da">

**Comment by Kysluss** [comment]
Hi @Hagriel !

If you add `restoreOnBlurIfEmpty={false}` to the `AutoComplete` component, it will change this behavior.  Below is an updated version of the component you're seeing in that codesandbox.  Let me know if that works for you and I'll close this issue.  If not, let me know how I can help and I'll take another look.

```js
export default function App() {
  const countries = [
    "nigeria",
    "japan",
    "india",
    "united states",
    "south korea",
  ];
  return (
    <Stack direction="column">
      <Text>Multi select with tags</Text>
      <AutoComplete openOnFocus multiple onChange={(vals) => console.log(vals)} restoreOnBlurIfEmpty={false}>
        <AutoCompleteInput placeholder="Search..." variant="filled">
          {({ tags }) =>
            tags.map((tag, tid) => (
              <AutoCompleteTag
                key={tid}
                label={tag.label}
                onRemove={tag.onRemove}
              />
            ))
          }
        </AutoCompleteInput>
        <AutoCompleteList>
          {countries.map((country, cid) => (
            <AutoCompleteItem
              key={`option-${cid}`}
              value={country}
              textTransform="capitalize"
              _selected={{ bg: "whiteAlpha.50" }}
              _focus={{ bg: "whiteAlpha.100" }}
            >
              {country}
            </AutoCompleteItem>
          ))}
        </AutoCompleteList>
      </AutoComplete>
    </Stack>
  );
}
```

**Comment by Hagriel** [comment]
Hi @Kysluss 
It's works
Thank you

**Comment by Kysluss** [comment]
Not a problem at all.  I'll go ahead and close this issue for now, but feel free to open a new one if anything else pops up.
