### ISSUE TITLE
The `value` prop does nothing

### ISSUE THREAD

**Issue by ThomasHickman** [anubra266/choc-autocomplete#235]
In the docs, the prop `value` in the `AutoComplete` component says that this prop is:
> value of the component in the controlled state

However, from testing this out and looking in the source code, it looks like the `value` property is only used in example code, or `types.ts`, or the `values` property:
![image](https://github.com/anubra266/choc-autocomplete/assets/6304200/b9a98fd7-93e5-4443-9f64-044a8f1dd50f)
and the `values` property is only used in `types.ts`:
![image](https://github.com/anubra266/choc-autocomplete/assets/6304200/629ce4e2-c510-4a3a-b3bc-e8e1e62698ec)

Indicating that the `AutoComplete` `value` property does nothing.

However, from looking around the codebase, it looks like if you pass in `value` to `AutoCompleteInput`, this will make sure you can use `AutoComplete` as a controlled component see:
https://github.com/anubra266/choc-autocomplete/blob/main/src/autocomplete-input.tsx#L62-L68

If this is true, it would be great if the documentation was updated to reflect this

**Comment by Kysluss** [comment]
Hi @ThomasHickman .  Sorry for the delay on getting back to you.

You're definitely right and this is probably one of the biggest causes for confusion with the component.  I'm thinking I should try and make the `value` prop actually do what it's supposed to.  It will take some testing to make sure I don't inadvertently introduce a separate bug.  I should have some time this weekend to work on it and appreciate any input you have on it.

**Comment by Kysluss** [comment]
[v5.3.0](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.3.0) has been released and fixes this issue.  I will be updating the docs and demo soon to show how you would implement form libraries like react-hook-form and formik.
