### ISSUE TITLE
use autocomplete with RHF

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#24]
This is more a question than a issue. I'm trying to use this component with [RHF](https://react-hook-form.com/)

In my first try I did this:

```js
     <Controller
        name={name}
        control={control}
        render={({ field: { onChange, onBlur, value } }) => (
            <AutoComplete freeSolo rollNavigation>
              <AutoCompleteInput onChange={onChange} onBlur={onBlur} value={value} />
            </AutoComplete>
        )}
```
I see the `defaultValue` in the input in the first render of the component, but if I select any item from the list, this is not updated in the input. Reading the docs, I think this is because is `onChange` in the `AutoComplete` component who handles that, so I have updated the code

```js
     <Controller
        name={name}
        control={control}
        render={({ field: { onChange, onBlur, value } }) => (
            <AutoComplete onChange={onChange} freeSolo rollNavigation>
              <AutoCompleteInput onBlur={onBlur} value={value} />
            </AutoComplete>
        )}
```

In this case, I don't see the `defaultValue` on the first render and I can't select a new value from the list.

So do you know what would be the way to use the component in controlled mode with RHF?

**Comment by anubra266** [comment]
I haven't used react hook form before, but I think I've got it to work here. 
https://codesandbox.io/s/react-hook-form-v7-controller-forked-e0n7n?file=/src/Chakra.js

**Comment by gepd** [comment]
You are closer, I did some changes and now is working!

I'll let the code here for other people looking the same

```js
    <Controller
        control={control}
        name="Choc"
        render={({ field }) => (
          <AutoComplete rollNavigation onChange={(val) => field.onChange(val)}>
            <AutoCompleteInput
              variant="filled"
              onChange={field.onChange}
              value={field.value}
              placeholder="Search..."
              defaultValue={field.value}
            />
            <AutoCompleteList>
              {options.map((option, oid) => (
                <AutoCompleteItem
                  key={`option-${oid}`}
                  value={option}
                  textTransform="capitalize"
                >
                  {option}
                </AutoCompleteItem>
              ))}
            </AutoCompleteList>
          </AutoComplete>
        )}
      />
```

The changes I did was update the `defaultValue` to `defaultValue={field.value}` add the `onChange` and `value` fields, this way it will change the value of the input when it is updated programatically as well

**Comment by gepd** [comment]
Actually this is not fully working yet, I shoudn't add the `value` and the `defaultValue` together, so when I remove the `defaultValue` prop I don't see `apple` (the current default value) in the form

https://codesandbox.io/s/react-hook-form-v7-controller-forked-rb4sk?file=/src/index.js

As you can see in the sandbox, when the form is loaded it prints `apple` in the console, but there is nothing in the input. If you press `change programatically` it works. So I just need to figure out how display the default value

**Comment by anubra266** [comment]
You don't need the value prop. Just the defaultValue

**Comment by gepd** [comment]
I need it, If don't use it, I can't control the input programmatically

**Comment by gepd** [comment]
Ok keep debuggin it I think is fully working 

The problem was here:

```js
<AutoComplete rollNavigation onChange={value => field.onChange(value)}>
```
The `onChange` was sending a empty string the first time, so I changed to

```js
<AutoComplete rollNavigation onChange={value => value && field.onChange(value)}>
```
and now all seems to be working as spected

This is the full code:

```js
  <Controller
        control={control}
        name="Choc"
        render={({ field }) => (
          <AutoComplete rollNavigation onChange={value => value && field.onChange(value)}>
            <AutoCompleteInput
              variant="filled"
              onChange={field.onChange}
              value={field.value}
              placeholder="Search..."
              defaultValue={field.value}
            />
            <AutoCompleteList>
              {options.map((option, oid) => (
                <AutoCompleteItem
                  key={`option-${oid}`}
                  value={option}
                  textTransform="capitalize"
                >
                  {option}
                </AutoCompleteItem>
              ))}
            </AutoCompleteList>
          </AutoComplete>
        )}
      />
```
