### ISSUE TITLE
Pressing enter when the autocomplete text box is closed selects the first entry, even when freeSolo is true

### ISSUE THREAD

**Issue by ThomasHickman** [anubra266/choc-autocomplete#240]
If you declare `freeSolo` in the AutoComplete component, it would be great if you could type in something, press `ESC` to exit the autocomplete box and expect the text you entered to get submitted unmodified in a form. However, currently, pressing enter in this situation completes to the first autocomplete entry.

Here's a screen-cast to demonstrate this:

[Screencast from 01-02-24 10:26:22.webm](https://github.com/anubra266/choc-autocomplete/assets/6304200/6c867a51-2d8a-4f17-97a1-3b6fa080080a)

**Comment by Kysluss** [comment]
Thank you for reporting this and for providing the screen recording.  It seems to do this even if you don't type anything into the `input` or even open it.  I'll get working on this.

**Comment by Kysluss** [comment]
This should be fixed in [v5.2.10](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.2.10).  Let me know if you still have issues and I'll reopen this issue.  Thank you for reporting the issue!
