### ISSUE TITLE
How to remove Pop Over "No Results Found"

### ISSUE THREAD

**Issue by tivothis** [anubra266/choc-autocomplete#245]
Hello there! First off, excellent work on this Autofill framework with Chakra.

This isn't a bug. I'm just trying to figure out how to remove the pop over display "No Results Found" that appears when you type in the input component and nothing stored in the Auto Complete List matches what's been typed. Is this possible? Apologies if this isn't the forum to ask, I just can't seem to find an answer to this through searching.

Thanks in advance.
Tony

![Screenshot 2024-02-26 at 6 01 14 PM](https://github.com/anubra266/choc-autocomplete/assets/90722230/2c4a0028-3873-44ed-a181-9d7fef566a88)

**Comment by anubra266** [comment]
@tivothis [`emptyState`](https://github.com/anubra266/choc-autocomplete#:~:text=false-,emptyState,-boolean%20%7C%20MaybeRenderProp) prop determines what shows there.

**Comment by tivothis** [comment]
Hello!

Thank you for getting back to me so promptly. Setting `emptyState` to false removes `No Options Found!` but the Pop Over div is still present, it just doesn't have text. Is it possible to hide the Pop Over div entirely if the onChange event from the user doesn't match anything in the Auto Fill List? I only want the Auto Fill List to render if there is something matching in the Auto Fill List.

**Comment by anubra266** [comment]
@tivothis Maybe `shouldRenderSuggestions` prop can help

**Comment by tivothis** [comment]
That worked. Thanks so much!
