### ISSUE TITLE
Autocomplete is showing a match if the 7 last char are equal even if the "x" other are not

### ISSUE THREAD

**Issue by mDeSimone-DFactorySrl** [anubra266/choc-autocomplete#251]
Hi all, sorry for bad eng.
My autocomplete is showing a match if a word contains the 7 chars that are at the end of the user input but it is not checking if the first one is equal.
if i search "USA1234567" i will get in return any value that ends in "1234567" or any other sequence of 7 chars like:
```
const countries = [
        "Random1234567",
        "Qwerty1234567",
        "Azerty1234567",
        "USA1234567",
    ];
```
![immagine](https://github.com/anubra266/choc-autocomplete/assets/167523235/16021a92-cabc-4c14-923a-e7624de0bd3e)

How can i return only value that strictly match at the starts?
I have tryed to search in the issue but i cannot find anything

my code is:
```
<AutoComplete openOnFocus>
  <AutoCompleteInput variant="filled" />
    <AutoCompleteList>
        {countries.map((country, cid) => (
            <AutoCompleteItem
                key={`option-${cid}`}
                value={country}
                textTransform="capitalize"
            >
                {country}
            </AutoCompleteItem>
        ))}
    </AutoCompleteList>
  </AutoComplete>
```

**Comment by Kysluss** [comment]
Hi @mDeSimone-DFactorySrl 

What you're seeing is a result of the default filter being `fuzzySearch`.  To get around it, you can pass in your own `filter` prop.  I am not at a computer to give an example at the moment, but I can post one once I am back.

**Comment by Kysluss** [comment]
Here is a link to another issue that has an example custom filter.

https://github.com/anubra266/choc-autocomplete/issues/249

**Comment by mDeSimone-DFactorySrl** [comment]
> Here is a link to another issue that has an example custom filter.
> 
> https://github.com/anubra266/choc-autocomplete/issues/249

Thanks i will try :)

**Comment by Kysluss** [comment]
Let me know if that works or not.  I'm back now and can drum up an example.
