### ISSUE TITLE
Expose Chakra Popover 'matchWidth' prop

### ISSUE THREAD

**Issue by rahultiru92** [anubra266/choc-autocomplete#252]
Chakra Popover has a `matchWidth` prop that allows for the dropdown to have `auto` width instead of matching the Popover Trigger. This is currently hardcoded to `true`:
https://github.com/anubra266/choc-autocomplete/blob/fcfab4eba6191f3a185f54df2c91f52c1f803b5e/src/autocomplete.tsx#L47

It would be convenient to expose the prop “matchWidth” from Chakra Popover to the consumer of Autocomplete. The prop could be optional while defaulting to true. That way all functionality remains the same as it currently is.

**Comment by Kysluss** [comment]
Hi @rahultiru92 

This is a good idea.  It should be available in the latest [v5.5.0](https://github.com/anubra266/choc-autocomplete/tree/v5.5.0) version
