### ISSUE TITLE
Keyboard navigation causes window to scroll in some configurations

### ISSUE THREAD

**Issue by EinarSnorrason** [anubra266/choc-autocomplete#253]
When the autocomplete form is not at the top or bottom of the page, keyboard navigation causes the window to scroll in addition to navigating the menu.

Tested on Chrome version 125.0.6422.142 on Windows 10.

This can be seen in [this codesandbox.](https://codesandbox.io/p/devbox/cool-dust-jrk70)

Menu at top of page (working properly):

https://github.com/anubra266/choc-autocomplete/assets/31321506/3f27127d-d017-4247-bb27-3972c5b9ad8d

Menu in middle of page (scrolling every time you press up or down):

https://github.com/anubra266/choc-autocomplete/assets/31321506/966792c2-b51c-4b3d-b834-7cf137c63069

**Comment by Kysluss** [comment]
Hi @EinarSnorrason 

I'll be honest, this has me a little puzzled.  Despite the arrow event not bubbling up, the browser seems to scroll the window regardless.  This one may take me a bit to figure out.  If you happen to figure it out in the meantime, feel free to submit a PR.

**Comment by EinarSnorrason** [comment]
Thanks! I'll take a look and see if I can spot anything.

**Comment by EinarSnorrason** [comment]
I found the culprit @Kysluss 

The problem is this block in autocomplete-item.tsx

`    useEffect(() => {
      if (isFocused && interactionRef.current === "keyboard")
        itemRef?.current?.scrollIntoView({
          behavior: "smooth",
          block: "center",
        });
    }, [isFocused, interactionRef]);
`

I assume the intention here was to make the selected element visible when you pressed the keyboard. But because the block variable is set to "center", the browser will try to move the item to the center of the window every time the keyboard is pressed.

Changing this to block: "nearest" changes the behaviour so it only scrolls the screen if the selected element isn't visible. I'll submit a PR with this change.
