### ISSUE TITLE
Styling of 'No options found!' message

### ISSUE THREAD

**Issue by MilordJan** [anubra266/choc-autocomplete#256]
It would be helpful to be able to somehow style the 'No options found!' message - through AutoCompleteItem props or otherwise - having it always maintain its default styling is not the best solution

**Comment by Kysluss** [comment]
Hi @MilordJan,

There is an `emptyState` prop that you can pass into the `Autocomplete` component to render your own message.  Would this work for what you're looking to do?

**Comment by Kysluss** [comment]
This has been added in [v5.6.0](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.6.0).  Let me know if there are other changes you are looking for.  Thank you for your suggestion.
