### ISSUE TITLE
Issue with pre focusing first item after the list changes

### ISSUE THREAD

**Issue by gbermudez1992** [anubra266/choc-autocomplete#257]
I have a long list that is pre filtered with a search bar. For some reason, the first option is not pre-selected when I type a new search, but instead it keeps the last one selected.

![Screenshot 2024-07-22 at 5 37 15 PM](https://github.com/user-attachments/assets/602050be-36eb-40aa-a639-02d2054876cc)
![Screenshot 2024-07-22 at 5 37 21 PM](https://github.com/user-attachments/assets/46a33973-fca7-4df7-923d-0223661c4013)

Is there some way to force the selection of the first element right after the list changes? The internal filter is also disabled with `disableFilter` prop.

**Comment by Kysluss** [comment]
Hi @gbermudez1992 ,

Would you be able to post a small reproduction of the issue?  Are you expecting the first item to be selected when you change your filter because it matches the value you typed in?

**Comment by gbermudez1992** [comment]
https://github.com/user-attachments/assets/0d77994b-6cf5-4685-8785-a9221d6b4dc5

**Comment by Kysluss** [comment]
I see.  So you're wanting the first item in the list to selected if you haven't explicitly selected something yet.  I think that's doable, but might not have time to work on it until the weekend.  I'll start poking around.

**Comment by Kysluss** [comment]
[v5.6.0](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.6.0) is out now with this included.  Thank you again for the PR.
