### ISSUE TITLE
`isInvalid` won't work for multiple select

### ISSUE THREAD

**Issue by fukamachi** [anubra266/choc-autocomplete#263]
`isInvalid` won't change the border color if `multiple` is specified.

### Screenshot

<img width="1305" alt="Screenshot 2024-08-12 at 16 38 40" src="https://github.com/user-attachments/assets/e0e48634-0174-479e-aeda-410b88bf11b9">

### Expected

<img width="574" alt="Screenshot 2024-08-12 at 16 38 48" src="https://github.com/user-attachments/assets/c233a06a-3094-4e4b-82d5-5abfb754585a">

**Comment by Kysluss** [comment]
Hi @fukamachi 

Thank you for reporting this and for the screenshot.  I was able to reproduce this and it does look like a bug.  A quick reproduction shows that it has something to do with the props being passed to the wrapper that is created when using multi-select.  I should be able to do some more digging soon and have a solution.

**Comment by Kysluss** [comment]
I was able to do some more testing this evening and this should be fixed in [v5.6.1](https://github.com/anubra266/choc-autocomplete/releases/tag/v5.6.1) now.  Thank you for the bug report @fukamachi !

**Comment by fukamachi** [comment]
Wow, how quick it was, thank you!
