### ISSUE TITLE
Ability to simply close the list programatically

### ISSUE THREAD

**Issue by joelclaudio** [anubra266/choc-autocomplete#264]
I've checked the documentation but I didn't find a function that could achieve this.

My use-case is as follows:
I have a list of elements and in the same list I have a "add button". When the user clicks the button it should do the following:
1. Add the new item to the state
2. Select that item
3. Close the items-list

<img width="307" alt="Screenshot 2024-08-13 at 12 00 12" src="https://github.com/user-attachments/assets/92621ec5-8864-4074-b739-01341c0c1739">

I am probably missing something in the API, but I am struggling with the 3rd part of this process, as the list remains open with the newly created item in display.
I want it the list to close after adding and selecting the new created item.

<img width="304" alt="Screenshot 2024-08-13 at 12 02 01" src="https://github.com/user-attachments/assets/f2b7256d-dfc1-469f-863f-ce8a1670caa1">

I have created a simple reproducible example (forked from the loading example) here:

https://codesandbox.io/s/choc-ui-chakra-autocomplete-loading-forked-h46qtl?file=/src/custom-debounce-loading.js

Thank you

**Comment by Kysluss** [comment]
Hi @joelclaudio 

Would the `creatable` prop along with the `AutoCompleteCreatable` component accomplish what you want?  Below is a quick example, but you can style the `AutoCompleteCreatable` by passing in your own render prop to it along with using the `value` prop supplied to it.

This isn't an exact repro of what you created, but should get you started.

```javascript
import React from "react";
import {
  AutoComplete,
  AutoCompleteCreatable,
  AutoCompleteInput,
  AutoCompleteItem,
  AutoCompleteList,
} from "@choc-ui/chakra-autocomplete";
import { Button, Flex } from "@chakra-ui/react";

const options = ["apple", "appoint", "zap", "cap", "japan"];

export default function App() {
  return (
      <AutoComplete rollNavigation creatable>
        <AutoCompleteInput
          variant="filled"
          placeholder="Search basic..."
          autoFocus
        />
        <AutoCompleteList>
          {options.map((option, oid) => (
            <AutoCompleteItem
              key={`option-${oid}`}
              value={option}
              textTransform="capitalize"
            >
              {option}
            </AutoCompleteItem>
          ))}
          <AutoCompleteCreatable>
            {({ value }) => <Button colorScheme='green'>Add {value}</Button> }
          </AutoCompleteCreatable>
        </AutoCompleteList>
      </AutoComplete>
  );
}
```

**Comment by joelclaudio** [comment]
The truth is that my setup is a little bit more complex that what I've shown. I was doing API requests on onChange events and have 2 other buttons that both add or change options on the AutoCompleteList.

Previous implementations with the creatable component wasn't compatible with this approach, but after your message I tried and reviewed my approach and now it's working perfectly.

The problem was that I was changing my options on the onChange event of the AutoComplete, so that would always mess everything else.

Thank you very much for the help @Kysluss

**Comment by Kysluss** [comment]
No problem @joelclaudio .  I am glad it ended up working for you.  If anything, you can also pass a render prop to `AutoCompleteList` and one of the methods that you get is `onClose`.  If you find yourself needing more control, feel free to open another issue.

```javascript
<AutoComplete>
    {({ isOpen, onOpen, onClose }) => (
...
    )}
</AutoComplete>
```
