### ISSUE TITLE
Clicking enter throws an error

### ISSUE THREAD

**Issue by karimcambridge** [anubra266/choc-autocomplete#29]
I use the autocomplete with list of google suggestions

say I type 'laptop' then click enter

![image](https://user-images.githubusercontent.com/4283893/126692474-72c042f0-f6f5-4dcd-a964-ed6ea1e24928.png)

Edit: This was on 3.5.4 btw, just updated

Edit: still happening on latest update

**Comment by anubra266** [comment]
Hi could you create a codesandbox reproduction of this issue? Thanks!

**Comment by anubra266** [comment]
Hi, I've not been able to reproduce this in the latest version, so I'm closing now.

**Comment by karimcambridge** [comment]
Agreed it seems good since v4 rewrite.
