### ISSUE TITLE
feature request: non-filterable item

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#3]
I'll like to have an option to avoid filter a item from the list

I'm using the creatable option, but I want to add an aditional option that will be always available in the list

```
- Option 1
- Option 2
---
- Add "Text"
- Create and Edit
```

I need to always show the `Create and Edit` option, so I was thinking in something like this:

```js
<AutoCompleteItem
  value="createAndEdit"
  textTransform="capitalize"
  alwaysShow
>
create and edit
</AutoCompleteItem>
```

**Comment by anubra266** [comment]
If you add the `freeSolo` and `creatable` prop to `AutoComplete`, entering an input that's not in the list shows automatically shows an `Add "input"` Item`

**Comment by gepd** [comment]
Yes, the creatable option is working as expected. I want to always display the `Create and Edit` option. So following the first example, if the input is set to `This is not in the list`, the result should be

```
- Add "This is not in the list"
- Create and Edit
```

**Comment by anubra266** [comment]
Okay...What do you think of `fixed` prop instead of `alwaysShow`

**Comment by gepd** [comment]
I think `fixed` is better, thanks!

**Comment by anubra266** [comment]
For the purpose of reusabilty, I won't be adding the fixed prop. I'll instead export a `FixedItem` component

**Comment by anubra266** [comment]
And I'm tweaking the `AutoCompleteList` so it accepts any component.
