### ISSUE TITLE
Item list should not open with `isReadOnly`

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#32]
If you set the `isReadOnly` prop to **true** in your `AutoCompleteInput` and focus it, it will open the list of items

**Comment by anubra266** [comment]
@gepd  Make sure you don't have the `openOnFocus` prop set to true

**Comment by gepd** [comment]
I'm using `suggestWhenEmpty` but even with this prop, I shouldn't be able to change the input as it's in read only mode don you think? it should be the same behavior with `openOnfocus`

**Comment by anubra266** [comment]
@gepd https://codesandbox.io/s/polished-pine-p49t4?file=/src/index.js

**Comment by gepd** [comment]
Ok I found the problem, I doesn't happen when you have the `multiple` prop, if you remove it and add `openOnFocus` and `isReadOnly` you will be able to change the value of the input https://codesandbox.io/s/hidden-cloud-8o53v?file=/src/index.js

**Comment by anubra266** [comment]
@gepd , I've looked at your codesandbox. you can't change the value of the input, but the suggestions come up because you have the `openOnFocus` prop.

**Comment by gepd** [comment]
This is what I mean

![autocomplete-bug](https://user-images.githubusercontent.com/7091609/127757313-2a0efb53-d264-4bb4-aa41-716bfe747126.gif)

**Comment by anubra266** [comment]
But why are you making the suggestions show, if you want the input to be readonly

**Comment by anubra266** [comment]
There could be unnecessary complexities from creating an algorithm to treat that prop differently. It's like wanting to add cases for all props an input could have.

**Comment by anubra266** [comment]
Point being, I would like to know your use case, then we can treat it from a better angle.

**Comment by gepd** [comment]
> But why are you making the suggestions show, if you want the input to be readonly

In my use case I'm using the component in a form that have a read and write state, when is in read mode all components in the form can't be updated, you can update it only in the write mode

> There could be unnecessary complexities from creating an algorithm to treat that prop differently. It's like wanting to add cases for all props an input could have.

But it feels a little inconsistent the behavior between `multiple` and `single`, when you try to do the same (in `multiple`) you can't, you press any item in the list and nothing happens

**Comment by anubra266** [comment]
Speaking of inconsistency, you might have forgotten to map the tags as children of the input.

**Comment by anubra266** [comment]
But your solution is the shouldRenderSuggestions prop, it's a method, so just return isEditable (or whatever represents editable state in your application) in that function

**Comment by anubra266** [comment]
Check the readme for a better understanding of that prop

**Comment by gepd** [comment]
I'll check that, it sounds like a better solution! Thanks!

**Comment by anubra266** [comment]
And for clarification, isReadOnly prop prevents users from typing into an input, not code from changing the value. It assumes developer might want to programmatically insert values that the end user cannot modify, so it limits your users, not you.

**Comment by anubra266** [comment]
Also what do you think of a disabled or read-only prop on the autocomplete itself. If it sounds nice, choose a name for the prop.

**Comment by gepd** [comment]
> Also what do you think of a disabled or read-only prop on the autocomplete itself. If it sounds nice, choose a name for the prop.

That would be cool, as almost all form component in chakra exposes a read only prop
you can name it same as the rest of the components `isReadOnly` what do you think?

**Comment by anubra266** [comment]
Done in [v.4.2.0](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.2.0)
