### ISSUE TITLE
AutoCompleteCreatable is shown on empty input

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#36]
When `AutoCompleteCreatable` is set with `openOnFocus` or `suggestWhenEmpty` the `AutoCompleteCreatable` is shown "empty"

```js
{({ value }) => <span>Add {value} to List</span>}
```
It's not really empty but `value` is, so I will end with an item called `Add to List`

Also I noticed that if the list have an option called `Apple` for example, it won't be filtered when the input is `Apple` as well

![image](https://user-images.githubusercontent.com/7091609/127780696-5da8dc8c-e6ea-4e2c-a618-d81720451385.png)

I think this stop to working recently

**Reproduction** https://codesandbox.io/s/react-hook-form-v7-controller-forked-rb4sk?file=/src/Chakra.js

**Comment by anubra266** [comment]
Do you mea, the creatable shows when input is empty

**Comment by anubra266** [comment]
Fixed in v4.3.2

**Comment by gepd** [comment]
Thanks @anubra266 the first issue is fixed, but the second one keeps happening. The example of the issue is in the image, shouldn't be possible to show the creatable option when the text of the input and one of the options are the same

**Comment by anubra266** [comment]
Fixed in [v4.3.3](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.3.3)

**Comment by anubra266** [comment]
@all-contributors please add @gepd for bug
