### ISSUE TITLE
How to remove italics from the no options text?

### ISSUE THREAD

**Issue by icy-meteor** [anubra266/choc-autocomplete#39]
![image](https://user-images.githubusercontent.com/22114682/127867640-0d78fd4d-7442-4386-bd5a-b45fd3be59d6.png)

I wish to remove the italics from the text - "No options found!" as it breaks the UI consistency. Any idea how to go about this?
Also, how can I change this text to say something else?

**Comment by anubra266** [comment]
There's an `emptyState` prop

**Comment by anubra266** [comment]
There's an `emptyState` prop

**Comment by anubra266** [comment]
`<AutoComplete emptyState={<Box> Nothing was found </Box>} />`

or even

`<AutoComplete emptyState={({value})=>(<Box> {value} was not found </Box>)} />`

**Comment by icy-meteor** [comment]
Perfect! Thanks, I couldn't find these in the documentation though. It wasn't very clear.
If you could update them with such examples, it would be helpful :)

**Comment by anubra266** [comment]
I'll try my best. It's just time. I wouldn't mind a PR though.
