### ISSUE TITLE
Possible to list all options when user focuses for the first time?

### ISSUE THREAD

**Issue by icy-meteor** [anubra266/choc-autocomplete#40]
<img src="https://user-images.githubusercontent.com/22114682/127870914-8e861613-13f1-488b-b2b4-bee96c564589.png" width="200">

I am looking for a behaviour that material-ui autocomplete takes care off - Ability to view all the menu items when the user focuses on the input box. But when the user starts typing, it starts showing just the filtered options.
 
This is useful in order for the user to view all the options as there is no way to view them at the moment without having to erase the entire text in the input box.

**Comment by anubra266** [comment]
just set the `openOnFocus` prop on the `AutoComplete` component

**Comment by anubra266** [comment]
Oh...you mean even when there's already text in the input. I'll put this in the next minor version, sometime today. But could you suggest a prop name that handles this? @icy-meteor

**Comment by icy-meteor** [comment]
Already have that prop. That opens the menu list on focus but the options inside it are still the filtered ones only. I need it to display all the options so that the user can see all the available options without having to backspace everything in input box.

**Comment by icy-meteor** [comment]
Haha, okay. Something like `listAllValuesOnFocus` makes sense to me.

**Comment by anubra266** [comment]
Cool. I'll comment here, when it's released.

**Comment by icy-meteor** [comment]
Thanks, appreciate your speed. Never seen anything like this before, excellent work mate.

**Comment by anubra266** [comment]
Available in [v4.4.0](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.4.0)

**Comment by icy-meteor** [comment]
Thanks. Tried it and works as expected but noticed a small glitch.
When I focus on the input box and then press the down arrow key on my keyboard, it doesn't reach till the last options but just stops midway.

**Comment by anubra266** [comment]
Ah...Think I know what's causing that.

**Comment by anubra266** [comment]
Fix released.

**Comment by icy-meteor** [comment]
Still seems buggy to me.

**Comment by anubra266** [comment]
Reproduce please.

**Comment by icy-meteor** [comment]
Yeah, that is the issue. I'm working on a closed source tool so it's hard for me to share. 
I'll find a way to give a codesandbox link soon

**Comment by icy-meteor** [comment]
https://codesandbox.io/s/choc-ui-autocomplete-kfu08?file=/src/App.tsx

The issue happens when 2 values have the same entry. For example, you can see that if you keep hitting the keyboard down arrow and as soon as you hit Item 11, it stops.

Now I am aware that you would ask me to have only unique values but in my use-case I have 2 same values but the IDs are different as "id" is my unique identifier key and not the "title" key.

This is also another reason why I suggested that label change in https://github.com/anubra266/choc-autocomplete/issues/41
so that users can define what the unique identifier needs to be, as users might end up in such a scenario.

Let me know if you have any questions, would be happy to help.

**Comment by anubra266** [comment]
If I follow this approach though, it'll have to be a breaking change.

**Comment by anubra266** [comment]
Closing this In favour of #41
