### ISSUE TITLE
Long option values getting cut 

### ISSUE THREAD

**Issue by icy-meteor** [anubra266/choc-autocomplete#42]
![image](https://user-images.githubusercontent.com/22114682/127874550-04829e04-e906-46d8-81b6-a646d07bca00.png)

Values that are longer than the `<AutoCompleteInput>` component width should have an ellipses at the end of the text instead of getting cut abruptly.

**Comment by icy-meteor** [comment]
`isTruncated` prop works as long as the input field is not focused. On focusing, it breaks again.

**Comment by anubra266** [comment]
Could you reproduce this in codesandbox please?

**Comment by icy-meteor** [comment]
Give me some time, I'll get back to you with the link.

**Comment by icy-meteor** [comment]
https://codesandbox.io/s/choc-ui-autocomplete-long-item-value-d8o70?file=/src/App.tsx

Here you go, you can check "Item 4" onwards.

**Comment by icy-meteor** [comment]
Okay, got it. Thanks.
