### ISSUE TITLE
Clicking <InputRightElement> does not expand the <AutoCompleteList>

### ISSUE THREAD

**Issue by icy-meteor** [anubra266/choc-autocomplete#43]
![image](https://user-images.githubusercontent.com/22114682/127876384-0cdecb4e-deb8-47ec-89e3-352f4ea53205.png)

 "@choc-ui/chakra-autocomplete": "^4.3.4"
 
 Clicking the `<InputRightElement>` isn't doing anything.

**Comment by anubra266** [comment]
Could you reproduce this in codesandbox please?

**Comment by icy-meteor** [comment]
Give me some time, I'll get back to you with the link.

**Comment by icy-meteor** [comment]
https://codesandbox.io/s/choc-ui-autocomplete-input-right-element-flp5b?file=/src/App.tsx

I have replaced the icon with some text for now but it's pretty much the same behaviour. Clicking the <InputRightElement> doesn't do anything.

**Comment by anubra266** [comment]
Hi @icy-meteor You don't have any onClick handler on the inputrightelement. What're you expecting it to do onClick.

**Comment by icy-meteor** [comment]
I want it to open the dropdown.

**Comment by anubra266** [comment]
Then you have to set an Onclick handler for that

**Comment by anubra266** [comment]
Check [this](https://github.com/anubra266/choc-autocomplete#accessing-the-internal-state) out. `onOpen` and `onClose` are also exposed as internal state.

**Comment by icy-meteor** [comment]
Yes, I saw this. I couldn't find what is the method exposed to open and close the popup. Neither were there any examples other than isOpen.
Is it onOpen and onClose? That doesn't sound right though.

**Comment by anubra266** [comment]
Yeah it's `onOpen` and `onClose`

**Comment by icy-meteor** [comment]
Okay, maybe we might want to fix the naming convention :) 
onOpen sounds more like a callback that gets fired when something is open. Doesn't sound like something that will trigger an open.

**Comment by anubra266** [comment]
@icy-meteor `onOpen` is the default return of Chakra's `useDisclosure`. and right, it's a callback that gets fired when something gets opened. But the verb open is just like a variable name, so we say, open the list, when the variable open is true.
Besides, changing this will be a breaking change.

**Comment by icy-meteor** [comment]
LGTM. Thanks.
