### ISSUE TITLE
[Question] The carriage return event will trigger an error (Cannot read property'disabled' of undefined)

### ISSUE THREAD

**Issue by StringKe** [anubra266/choc-autocomplete#45]
demo: https://codesandbox.io/s/choc-ui-packages-codesandbox-forked-0ziuu?file=/src/App.js

`Uncaught TypeError: Cannot read property 'disabled' of undefined`

Open the demo link and enter some content at random, and press Enter, Don't use the mouse to select content

I don’t know why this is caused. I’m trying to implement a search box with autocomplete, and then some keywords will be loaded from the backend to the user.

**Comment by StringKe** [comment]
About the performance of the upgraded components
1. When the line selection is not matched, pressing Enter will not trigger the OnChange event
2. After selecting a match, typing anything will trigger the OnChange event

https://codesandbox.io/s/choc-ui-packages-codesandbox-forked-0ziuu?file=/src/App.js

I want to use `choc-autocomplete` to implement a search box like google https://www.google.com

My implementation logic
1. Monitor input and request keywords from the backend
2. When the user clicks on the keyword / presses enter, the search query is triggered

> English is not my native language; please excuse typing errors.

**Comment by anubra266** [comment]
There's an `onSelectOption` prop, that is called whenever an option is selected.

**Comment by StringKe** [comment]
> There's an `onSelectOption` prop, that is called whenever an option is selected. You could trigger the search anytime, this method gets called.

`onSelectOption` is only triggered when it is selected, maybe the carriage return of input should trigger `onChange`, whether it is selected or not?

**Comment by anubra266** [comment]
The autocomplete onChange prop is reserved for when the value of the autocomplete component changes.

**Comment by anubra266** [comment]
We could add a new prop for this use case, maybe on the InputComponent.

**Comment by anubra266** [comment]
if you need `onInputChange` you could just do onChange on the autocomplete input component.

**Comment by anubra266** [comment]
But you could expatiate more on `emitEnter`

**Comment by StringKe** [comment]
If `emitEnter` is true, the `onChange` event of `<AutoComplete/>` should be triggered when the enter is pressed

**Comment by StringKe** [comment]
In the current version, if I monitor the input of `input` and select an option, continuing to input anything will trigger the `onChange` event of `<AutoComplete/>

**Comment by anubra266** [comment]
> In the current version, if I monitor the input of `input` and select an option, continuing to input anything will trigger the `onChange` event of `

I don't get that part @StringKe, isn't the onChange (of the input) triggered anytime you type, even before selection.

**Comment by StringKe** [comment]
> > In the current version, if I monitor the input of `input` and select an option, continuing to input anything will trigger the `onChange` event of `
> 
> I don't get that part @StringKe, isn't the onChange (of the input) triggered anytime you type, even before selection.

You can open this link to view the source code https://codesandbox.io/s/choc-ui-packages-codesandbox-forked-0ziuu?file=/src/App.js:666-701

Or open the link below to view the video
https://cln.sh/vORDzt

**Comment by anubra266** [comment]
@StringKe  Just fixed the onChange bug.

**Comment by StringKe** [comment]
I updated to the latest version, input and select an option will appear the following error 

```
Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
     at input
```
     
Demo: https://codesandbox.io/s/choc-ui-packages-codesandbox-forked-0ziuu?file=/src/App.js

Can you tell me why this error is?
thank you.
