### ISSUE TITLE
[Feature] The option is empty copy can be modified

### ISSUE THREAD

**Issue by StringKe** [anubra266/choc-autocomplete#47]
https://github.com/anubra266/choc-autocomplete/blob/4d0a1c0d3dc82b492a7914e4da10c76c915b25df/src/components/empty-state.tsx#L9

I need to do i18n support, but the hint here seems to be fixed, I can’t modify it

**Comment by anubra266** [comment]
It's not fixed.

See answer in #39

**Comment by StringKe** [comment]
OK, thanks
