### ISSUE TITLE
The component doesn't work in build

### ISSUE THREAD

**Issue by subzero79** [anubra266/choc-autocomplete#51]
I though  it was going crazy. I am fetching the list and the already selected items from external API. Everything worked in localhost but not in build. In my case i use next with TS

I created this codesandbox with next and TS

https://codesandbox.io/s/k0qfj

values are hardcoded there. An it works fine. 

This is the same code deployed to vercel directly from codesandbox

https://csb-k0qfj-subzero79.vercel.app/

Thanks again for your work

**Comment by anubra266** [comment]
Damn. You're right @subzero79. I currently have no idea why, but I'll look into it.

**Comment by anubra266** [comment]
Found it @subzero79 Releasing a fix now.

**Comment by subzero79** [comment]
Thanks. Btw how do you start debugging something like this ?

**Comment by anubra266** [comment]
@subzero79 This time, it was lucky instincts. But the right way to get stuff like this is with automated testing. I haven't done that cause I'm still learning it.

**Comment by anubra266** [comment]
FIxed in [v4.5.4](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.5.4)

**Comment by tell-y** [comment]
Hi I'm also facing this issue with @choc-ui/chakra-autocomplete@4.5.10 in Nextjs@11.1.2 / react@17.0.2.
@anubra266 

How about your current status? @subzero79

**Comment by subzero79** [comment]
It works fine for me now in my production site.

**Comment by tell-y** [comment]
Thank you.
I'll struggle to investigate it...

**Comment by anubra266** [comment]
@tell-y Are you able to reproduce the issue in codesandbox
