### ISSUE TITLE
How to select the first option in the carriage return event?

### ISSUE THREAD

**Issue by StringKe** [anubra266/choc-autocomplete#53]
I hope that `<AutoComplete/>` can correctly trigger the `Enter event` regardless of whether the option is selected or not

**Comment by anubra266** [comment]
would an `onEnterKeydown` event prop be okay?

**Comment by StringKe** [comment]
I try to listen to the `onKeypress` event of `AutoCompleteInput`, but I can’t listen to the `Enter` event properly anyway

**Comment by anubra266** [comment]
You should do something like this:

```js
onKeyDown: e => {
          const { key } = e;
          if (key === "Enter") {
            
            //Whatever you want to do.

            e.preventDefault();
            
            // If you want to prevent the default actions done by the package, such as selecting an option.
            e.stopPropagation()

          }
```

**Comment by StringKe** [comment]
> would an `onEnterKeydown` event prop be okay?

Does `react` or `charka` have this event?

**Comment by StringKe** [comment]
> You should do something like this:
> 
> ```js
> onKeyDown={ e => {
>           const { key } = e;
>           if (key === "Enter") {
>             
>             //Whatever you want to do.
> 
>             e.preventDefault();
>             
>             // If you want to prevent the default actions done by the package, such as selecting an option.
>             e.stopPropagation()
> 
> }}
> ```

I understand, thank you
