### ISSUE TITLE
React does not recognize the `rollNavigation` prop on a DOM element.

### ISSUE THREAD

**Issue by DeiverJC** [anubra266/choc-autocomplete#54]
Hello, This property is causing an error when rendering the input. I'm using NextJS.

**Comment by anubra266** [comment]
Hi! what version are you using?

**Comment by DeiverJC** [comment]
I'm using the version 4.5.5. Even in your codesandbox example I get the same error in console [Chakra Autocomplete Demo](https://codesandbox.io/s/chakra-autocomplete-demo-elurs)

**Comment by anubra266** [comment]
Hi! @DeiverJC the error occurs because your `rollNavigation` is not on the `AutoComplete` component. you might have put it on the `AutoCompleteList` component instead, that was the mistake in the codesandbox demo.

**Comment by DeiverJC** [comment]
Thanks a lot.
