### ISSUE TITLE
Not shown selected value after selecting option

### ISSUE THREAD

**Issue by tell-y** [anubra266/choc-autocomplete#55]
In v4.5.5 latest version, when you select an option, you can not see the value.

Check the representation using [demo](https://codesandbox.io/s/chakra-autocomplete-demo-elurs) with v4.5.5

Thanks

**Comment by tabvn** [comment]
the same bug.

**Comment by anubra266** [comment]
@tell-y @tabvn this should be fixed in [v4.5.9](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.5.9)
