### ISSUE TITLE
Demo with latest version

### ISSUE THREAD

**Issue by tell-y** [anubra266/choc-autocomplete#56]
Why don't you deploy the [demo](https://codesandbox.io/s/chakra-autocomplete-demo-elurs) with the latest version after the new release?

**Comment by anubra266** [comment]
I'm having exams, can't work on this yet. PR's will be appreciated though.

Solution

Create a demo folder in the repository that holds the codesandbox demo, and uses the latest version.
The demo link in the readme, now won't link to a premade sandbox, but would use the `githubbox` method to open the demo folder in codesandbox

https://githubbox.com/anubra266/choc-autocomplete/demo
