### ISSUE TITLE
AutoCompleteCreatable doesn't work with AutoCompleteInput tags

### ISSUE THREAD

**Issue by jamesopti** [anubra266/choc-autocomplete#62]
When selecting the creatable, the render function is passed an object with only the remove function (`{ onRemove }` )

I may be missing something, but a Codesandbox demo of creatable with tags would be great!

**Comment by anubra266** [comment]
You're right. Creatable does not provide the right object. Thanks for creating this issue

**Comment by yashrank4** [comment]
![Screenshot from 2021-09-04 19-09-23](https://user-images.githubusercontent.com/72604380/132096426-02b1f09c-bbec-49a6-bcbc-a21a9059c13c.png)


I am also facing same issue. values are not setting up in tags in  type "UseAutoCompleteReturn"
This causing the empty rendering span with no value inside.

**Comment by anubra266** [comment]
@jamesopti @yashrank4 this should be fixed in [v4.5.10](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.5.10)
