### ISSUE TITLE
feat (multiselect): API methods for removing one item or all items

### ISSUE THREAD

**Issue by jamesopti** [anubra266/choc-autocomplete#64]
When using multi-select, it would be nice to have an API to remove a single selected item or to clear all items (reset) from _outside_ the component.

I think the most idiomatic React way to do this in the current architecture of AutoComplete would be to expose an `onReady` or `init` callback which provides these methods.

```ts
<AutoComplete
  onReady={({ getItems, removeItem, reset }) => {
    // Store reference to API methods for later use
  }}
```

**Comment by anubra266** [comment]
Hi @jamesopti, I might be quite naive on this topic, so could you expatriate more on the features we're trying to achieve here. Thsnkd.

**Comment by jamesopti** [comment]
> Hi @jamesopti, I might be quite naive on this topic, so could you expatriate more on the features we're trying to achieve here. Thsnkd.

Sure! I have 2 examples in mind here:

**_For clear_**
1 - A "Submit" button for the entries should be able to reset the internal state of the component.
2 - A "Clear/Reset" button in the UI that lives outside the AutoComplete component. 

Right now, the hack to do this is to change the `key` prop to the component (we're incrementing by 1)

**_For removeItem_**
1 - Pressing backspace when the input is empty should delete the last tag in the list

**_For getItems_**
1 - Would be nice to have a list of the currently selected items accessible outside the component

**Comment by anubra266** [comment]
Oh...thanks @jamesopti I now understand what you;re asking for.

**Comment by anubra266** [comment]
I wanna perfectly get it right @jamesopti that onReady is a function that is run when the component is rendered, and provides this methods you'll like to use from the component.

**Comment by anubra266** [comment]
You can now do 
```js
 <AutoComplete>
          {({ 
                isOpen: boolean;
                onClose: () => void;
                onOpen: () => void;
                removeItem: (itemValue: Item["value"]) => void;
                resetItems: (focusInput: boolean) => void;
                tags: Tag[];
          }) => (
```
