### ISSUE TITLE
AutoCompleteTag resizes the AutoCompleteInput component

### ISSUE THREAD

**Issue by Overdrive141** [anubra266/choc-autocomplete#65]
When using multiple prop in AutoComplete, if I choose multiple tags then it resizes the entire AutoCompleteInput component and makes it wider/longer. Can there be a way to solve this? 

Alternatively, can we use tags outside AutoCompleteInput and above that component so that it does not resize the parent.

**Comment by wilsonfaustino** [comment]
It would be great to have the possibility to use AutoCompleteTags outside the Input. Above or below.

**Comment by anubra266** [comment]
> It would be great to have the possibility to use AutoCompleteTags outside the Input. Above or below.

It's done now @wilsonfaustino

**Comment by anubra266** [comment]
@Overdrive141 The alternative is now available, but you can also set a fixed size on the input's width to prevent autogrowing.

**Comment by anubra266** [comment]
Feel free to reopen this if any issues persit. Closing now.
