### ISSUE TITLE
Basic Selector with RHF

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#77]
I need help to use this library with `react-hook-form`

I want to keep showing the `label` parameter while I'm using the `value` in RHF. Currently if I select an item from the list it will display the `value` as `label`. Maybe I don't understand well the use of label and value

This is the reproduction sandbox

https://codesandbox.io/s/lucid-fire-jq1nj?file=/src/basic.js

**Comment by anubra266** [comment]
Hi @gepd It's not working because you have `children` in your `AutocompleteItem`. The `children` is considered before the `label`. So change
```html
<AutoCompleteItem
                    key={`option-${oid}`}
                    value={`val-${option}`}
                    label={option}
                    textTransform="capitalize"
                  >
                    {option}
                  </AutoCompleteItem>
```
to
```js
<AutoCompleteItem
                    key={`option-${oid}`}
                    value={`val-${option}`}
                    label={option}
                    textTransform="capitalize"
                  />
```

**Comment by gepd** [comment]
I have updated the example but I'm getting the same result; the input is updated with the value selected (value in the `value` prop)

You can see the behavior in the same link

**Comment by anubra266** [comment]
Oh @gepd you're using a controlled input. You don't need `value={value}` on the input.

**Comment by gepd** [comment]
Thanks @anubra266  removing `value` from the input solved my problem. 

What do you think of put sandbox with this kind of examples in the docs? I can send you the links so you can fork it if you want

**Comment by anubra266** [comment]
> What do you think of put sandbox with this kind of examples in the docs? I can send you the links so you can fork it if you want

Hi @gepd there's a codesandbox link in the readme after the examples that is created from the demo folder in the repo, you can make a PR, and add your examples to that folder, thanks!

**Comment by anubra266** [comment]
> What do you think of put sandbox with this kind of examples in the docs? I can send you the links so you can fork it if you want

Hi @gepd there's a codesandbox link in the readme after the examples that is created from the demo folder in the repo, you can make a PR, and add your examples to that folder, thanks!

**Comment by gepd** [comment]
I'll re-open this issue as I have one more doubt, I can't set the default value with my code. I've tried to add the `defaultValue` to the `AutoComplete` Tag and `AutoCompleteInput` but I neither of the options seems to work and there no example for that case in the folder example

**Comment by gepd** [comment]
> I have one more doubt, I can't set the default value with my code. I've tried to add the `defaultValue` to the `AutoComplete` Tag and `AutoCompleteInput` but neither of the options seems to work and there no example for that case in the folder example

Hey @anubra266 should I create a new issue for this problem?
