### ISSUE TITLE
Can't apply on form formik

### ISSUE THREAD

**Issue by quangtin** [anubra266/choc-autocomplete#82]
I'm using charkui and form formik. When I apply your autocomplete field with form formik, it show a error "Cannot read properties of undefined (reading 'persist')". After reproducing, I recognized that the onBlur is not passed a args (e) like onChange.
Block code happend error:

onBlur: function onBlur(e) {

          var _inputWrapperRef$curr;
          runIfFn(_onBlur);
          var listIsFocused = e.relatedTarget === (listRef == null ? void 0 : listRef.current);
          var inputWrapperIsFocused = (_inputWrapperRef$curr = inputWrapperRef.current) == null ? void 0 : _inputWrapperRef$curr.contains(e.relatedTarget);

          if (!listIsFocused && !inputWrapperIsFocused) {
            var _getLastItem;

            if (closeOnBlur) onClose();
            if (!values.includes(e.target.value) && !freeSolo) setQuery((_getLastItem = getLastItem(values)) != null ? _getLastItem : "");
          }`   

}
Image:
![image](https://user-images.githubusercontent.com/17883559/136117804-94d2a75f-0d0c-43b0-897e-4b10443ab15f.png)

**Comment by valerius21** [comment]
having the same problem when using the `Field` Tag
