### ISSUE TITLE
defaultValue not working

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-autocomplete#88]
> I have one more doubt, I can't set the default value with my code. I've tried to add the `defaultValue` to the `AutoComplete` Tag and `AutoCompleteInput` but neither of the options seems to work and there no example for that case in the folder example

Hey @anubra266 should I create a new issue for this problem?

_Originally posted by @gepd in https://github.com/anubra266/choc-autocomplete/issues/77#issuecomment-944996953_

**Comment by gepd** [comment]
With the last release, the defaultValue stopped to working in uncontrolled mode

**Comment by anubra266** [comment]
@gepd please create a codesandbox reproduction

**Comment by cbfn** [comment]
You can add the default value here: 

```
<AutoComplete openOnFocus defaultValue="value">
...
</AutoComplete>
```
