### ISSUE TITLE
Is it a bug or is it a feature?

### ISSUE THREAD

**Issue by anilanar** [anubra266/choc-autocomplete#91]
I'm having trouble making `AutoComplete` work in a sensible way.

Looking at the `codesandbox` example, it doesn't work in a sensible way either.

Could you provide `codesandbox` examples on how to use `AutoComplete` so that the input field can be edited freely by typing? Currently input fields in `codesandbox` examples are not editeable at all. In fact, the `Basic` example is quite useless. Cannot type anything, cannot select any options.

**Comment by anubra266** [comment]
@anilanar there was a broken release, should be fixed in [v4.11.2](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.11.2)
