### ISSUE TITLE
Next item with Tab

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#94]
If you have multiples inputs, you can go to the next one pressing`tab`, when you are in the autcomplete component, it opens the option list, but when you already selected an option, there is no way to go to the next one (with the keyboard)

Is there a way to improve this?

![autocomplete-bug](https://user-images.githubusercontent.com/7091609/139592476-d91898f6-9283-48e8-99a6-291c8e92f12a.gif)

Other small issue is, the component seems to have a div with a `tabindex="0"`, the first element to be selected is the div, instead of the input

**Comment by anubra266** [comment]
@gepd, you can navigate the items with the arrow keys

**Comment by gepd** [comment]
My issue is not navigate with elements of the list, I do that without problem, what I'm trying to resolve is the navigation between autocomplete components only with the keyboard, I know when you get the focus it will display the list, but after select an option I can't go to the next element (input) of the form, the only way to that is the cursor

**Comment by anilanar** [comment]
Yeah basically `Autocomplete` traps the focus after making a selection.

**Comment by tmarnet** [comment]
I have the same issue, which is not good for a11y 😞 
Do we have any update on this ?
