### ISSUE TITLE
Input value, switching from item label to value after focus in and out.

### ISSUE THREAD

**Issue by anubra266** [anubra266/choc-autocomplete#95]
Expected behaviour is the same of @selvinkuik , so when I search for item that doesn't exists and than focus out from input, the value of input must not change (empty or previous selected item).
This behaviour occurs correctly when items have simple `value` parameter.

Thank you

_Originally posted by @f-laino in https://github.com/anubra266/choc-autocomplete/issues/68#issuecomment-962043271_

**Comment by Kysluss** [comment]
@f-laino are you still having this issue?  Using the scenario you described, it looks like the previously selected value stays.

* Select an item
* Focus input again and type a value that doesn't exist
* Blur input without selecting an item
* Original value remains

If `freeSolo=true`, the new value you enter that does not exist will remain.
