### ISSUE TITLE
Array as default value in controlled mode does not show the right tags

### ISSUE THREAD

**Issue by gepd** [anubra266/choc-autocomplete#99]
If I set an array as default value (in controlled mode), it doesn't work as expected, if I set an string, it work but by default, I will have multiples values

reproduction: https://codesandbox.io/s/lucid-fire-jq1nj?file=/src/basic.js

**Comment by anubra266** [comment]
@gepd strangest thing ever, but I added an example, and mine works [here](https://codesandbox.io/s/boring-mayer-tt8tn?file=/src/basic.js). Can't even find the difference yet

**Comment by anubra266** [comment]
@gepd use `values` not `value` in multiple mode.

**Comment by anubra266** [comment]
Jusr released a version that supports `value` in multiple mode [_v4.12.0_](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.12.0)

**Comment by gepd** [comment]
thanks @anubra266 !
